package com.livelearn.ignorance.model.db.dbdao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.livelearn.ignorance.model.db.dbentity.Department;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTMENT".
*/
public class DepartmentDao extends AbstractDao<Department, Long> {

    public static final String TABLENAME = "DEPARTMENT";

    /**
     * Properties of entity Department.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sub_dept_id = new Property(1, String.class, "sub_dept_id", false, "SUB_DEPT_ID");
        public final static Property Dept_id = new Property(2, String.class, "dept_id", false, "DEPT_ID");
        public final static Property Dept_name = new Property(3, String.class, "dept_name", false, "DEPT_NAME");
        public final static Property Sub_dept_name = new Property(4, String.class, "sub_dept_name", false, "SUB_DEPT_NAME");
    }


    public DepartmentDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTMENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SUB_DEPT_ID\" TEXT UNIQUE ," + // 1: sub_dept_id
                "\"DEPT_ID\" TEXT," + // 2: dept_id
                "\"DEPT_NAME\" TEXT," + // 3: dept_name
                "\"SUB_DEPT_NAME\" TEXT);"); // 4: sub_dept_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTMENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Department entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sub_dept_id = entity.getSub_dept_id();
        if (sub_dept_id != null) {
            stmt.bindString(2, sub_dept_id);
        }
 
        String dept_id = entity.getDept_id();
        if (dept_id != null) {
            stmt.bindString(3, dept_id);
        }
 
        String dept_name = entity.getDept_name();
        if (dept_name != null) {
            stmt.bindString(4, dept_name);
        }
 
        String sub_dept_name = entity.getSub_dept_name();
        if (sub_dept_name != null) {
            stmt.bindString(5, sub_dept_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Department entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sub_dept_id = entity.getSub_dept_id();
        if (sub_dept_id != null) {
            stmt.bindString(2, sub_dept_id);
        }
 
        String dept_id = entity.getDept_id();
        if (dept_id != null) {
            stmt.bindString(3, dept_id);
        }
 
        String dept_name = entity.getDept_name();
        if (dept_name != null) {
            stmt.bindString(4, dept_name);
        }
 
        String sub_dept_name = entity.getSub_dept_name();
        if (sub_dept_name != null) {
            stmt.bindString(5, sub_dept_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Department readEntity(Cursor cursor, int offset) {
        Department entity = new Department( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sub_dept_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dept_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dept_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // sub_dept_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Department entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSub_dept_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDept_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDept_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSub_dept_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Department entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Department entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Department entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
