package com.livelearn.ignorance.model.db.dbdao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.livelearn.ignorance.model.db.dbentity.Hospital;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOSPITAL".
*/
public class HospitalDao extends AbstractDao<Hospital, Long> {

    public static final String TABLENAME = "HOSPITAL";

    /**
     * Properties of entity Hospital.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HOSPITAL_ID = new Property(1, String.class, "HOSPITAL_ID", false, "HOSPITAL__ID");
        public final static Property HOSPITAL_NAME = new Property(2, String.class, "HOSPITAL_NAME", false, "HOSPITAL__NAME");
        public final static Property CITY_CODE = new Property(3, String.class, "CITY_CODE", false, "CITY__CODE");
        public final static Property HOSPITAL_STS = new Property(4, String.class, "HOSPITAL_STS", false, "HOSPITAL__STS");
    }


    public HospitalDao(DaoConfig config) {
        super(config);
    }
    
    public HospitalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOSPITAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOSPITAL__ID\" TEXT UNIQUE ," + // 1: HOSPITAL_ID
                "\"HOSPITAL__NAME\" TEXT," + // 2: HOSPITAL_NAME
                "\"CITY__CODE\" TEXT," + // 3: CITY_CODE
                "\"HOSPITAL__STS\" TEXT);"); // 4: HOSPITAL_STS
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOSPITAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Hospital entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HOSPITAL_ID = entity.getHOSPITAL_ID();
        if (HOSPITAL_ID != null) {
            stmt.bindString(2, HOSPITAL_ID);
        }
 
        String HOSPITAL_NAME = entity.getHOSPITAL_NAME();
        if (HOSPITAL_NAME != null) {
            stmt.bindString(3, HOSPITAL_NAME);
        }
 
        String CITY_CODE = entity.getCITY_CODE();
        if (CITY_CODE != null) {
            stmt.bindString(4, CITY_CODE);
        }
 
        String HOSPITAL_STS = entity.getHOSPITAL_STS();
        if (HOSPITAL_STS != null) {
            stmt.bindString(5, HOSPITAL_STS);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Hospital entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HOSPITAL_ID = entity.getHOSPITAL_ID();
        if (HOSPITAL_ID != null) {
            stmt.bindString(2, HOSPITAL_ID);
        }
 
        String HOSPITAL_NAME = entity.getHOSPITAL_NAME();
        if (HOSPITAL_NAME != null) {
            stmt.bindString(3, HOSPITAL_NAME);
        }
 
        String CITY_CODE = entity.getCITY_CODE();
        if (CITY_CODE != null) {
            stmt.bindString(4, CITY_CODE);
        }
 
        String HOSPITAL_STS = entity.getHOSPITAL_STS();
        if (HOSPITAL_STS != null) {
            stmt.bindString(5, HOSPITAL_STS);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Hospital readEntity(Cursor cursor, int offset) {
        Hospital entity = new Hospital( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // HOSPITAL_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // HOSPITAL_NAME
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // CITY_CODE
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // HOSPITAL_STS
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Hospital entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHOSPITAL_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHOSPITAL_NAME(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCITY_CODE(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHOSPITAL_STS(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Hospital entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Hospital entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Hospital entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
