package com.livelearn.ignorance;

// DO NOT EDIT: This file is automatically generated.
public class VersionInfo {
    public static final String LIBRARY_VERSION = "922d7e9";
    public static final String BUILD = "922d7e9";
}
