package com.livelearn.ignorance;

// DO NOT EDIT: This file is automatically generated.
public class VersionInfo {
    public static final String LIBRARY_VERSION = "ccc0b08";
    public static final String BUILD = "ccc0b08";
}
