package com.livelearn.ignorance;

// DO NOT EDIT: This file is automatically generated.
public class VersionInfo {
    public static final String LIBRARY_VERSION = "df9602a";
    public static final String BUILD = "df9602a";
}
